Name:           ros-hydro-nao-gazebo-plugin
Version:        0.0.3
Release:        0%{?dist}
Summary:        ROS nao_gazebo_plugin package

Group:          Development/Libraries
License:        Apache 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-gazebo-plugins
Requires:       ros-hydro-gazebo-ros
Requires:       ros-hydro-gazebo-ros-control
Requires:       ros-hydro-nao-control
Requires:       ros-hydro-nao-description
Requires:       ros-hydro-ros-control
Requires:       ros-hydro-ros-controllers
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-gazebo-ros
BuildRequires:  ros-hydro-nao-description
BuildRequires:  ros-hydro-ros-control
BuildRequires:  ros-hydro-ros-controllers

%description
The nao_gazebo_plugin package

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Thu Dec 04 2014 Mikael Arguedas <mikael.arguedas@gmail.com> - 0.0.3-0
- Autogenerated by Bloom

* Mon Oct 27 2014 Mikael Arguedas <mikael.arguedas@gmail.com> - 0.0.2-0
- Autogenerated by Bloom

* Sun Sep 28 2014 Mikael Arguedas <mikael.arguedas@gmail.com> - 0.0.1-0
- Autogenerated by Bloom

